import datetime
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Text, Float, DateTime
from sqlalchemy.orm import relationship
from app.database import Base

class User(Base):
    """
    User credentials and authentication details.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)

    courses = relationship("Course", back_populates="user", cascade="all, delete-orphan")
    daily_activities = relationship("DailyActivity", back_populates="user", cascade="all, delete-orphan")
    insights = relationship("KnowledgeInsight", back_populates="user", cascade="all, delete-orphan")
    user_settings = relationship("UserSettings", uselist=False, back_populates="user", cascade="all, delete-orphan")
    user_profile = relationship("UserProfile", uselist=False, back_populates="user", cascade="all, delete-orphan")

class Course(Base):
    """
    Represents a full multi-chapter dynamic learning course generated by AI.
    """
    __tablename__ = "courses"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True)
    title = Column(String, index=True)
    short_title = Column(String, nullable=True)
    description = Column(String)
    course_description = Column(Text, nullable=True)
    level = Column(String, nullable=True)
    hours = Column(Integer, nullable=True)
    total_estimated_hours = Column(Integer, nullable=True)
    sessions = Column(Integer, nullable=True)
    target_user_summary = Column(Text, nullable=True)
    course_goal = Column(Text, nullable=True)
    learning_outcomes = Column(Text, nullable=True)  # JSON array
    prerequisites = Column(Text, nullable=True)  # JSON array
    chat_summary = Column(Text, nullable=True)
    color = Column(String, nullable=True, default="purple")
    cover_image = Column(String, nullable=True)

    # Global publishing state — when True this course is visible in the
    # shared Global Courses catalog for other users to enroll in.
    is_published = Column(Boolean, default=False, nullable=False, index=True)
    published_at = Column(DateTime, nullable=True)
    # Lineage: if this course was cloned via enrollment, points to the
    # original globally-published course. NULL for originally authored courses.
    source_course_id = Column(Integer, ForeignKey("courses.id"), nullable=True, index=True)

    user = relationship("User", back_populates="courses")
    items = relationship("OutlineItem", back_populates="course", cascade="all, delete-orphan")
    chat_messages = relationship("CourseChatMessage", back_populates="course", cascade="all, delete-orphan", order_by="CourseChatMessage.id")

class CourseChatMessage(Base):
    """
    Represents conversational logs between the student and their smart coach for a specific course.
    """
    __tablename__ = "course_chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, ForeignKey("courses.id"))
    role = Column(String)
    content = Column(Text)
    is_summarized = Column(Boolean, default=False)

    course = relationship("Course", back_populates="chat_messages")

class OutlineItem(Base):
    """
    Represents an individual session/lesson within a chapter.
    Holds generated session Markdown text and study duration statistics.
    """
    __tablename__ = "outline_items"

    id = Column(Integer, primary_key=True, index=True)
    course_id = Column(Integer, ForeignKey("courses.id"))
    session_id = Column(String, nullable=True)
    chapter = Column(String, nullable=True)
    chapter_id = Column(String, nullable=True)
    title = Column(String)
    description = Column(Text, nullable=True)
    learning_objectives = Column(Text, nullable=True)  # JSON array
    key_concepts = Column(Text, nullable=True)  # JSON array
    order = Column(Integer)
    is_completed = Column(Boolean, default=False)
    content = Column(Text, nullable=True)
    study_time = Column(Integer, default=0)       # in seconds
    completed_at = Column(String, nullable=True)  # ISO format string

    course = relationship("Course", back_populates="items")

class DailyActivity(Base):
    """
    Aggregates learning durations per day (YYYY-MM-DD) for analytics heatmaps.
    """
    __tablename__ = "daily_activity"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True)
    date = Column(String, index=True)            # YYYY-MM-DD
    study_time = Column(Integer, default=0)      # in seconds

    user = relationship("User", back_populates="daily_activities")

class KnowledgeInsight(Base):
    """
    Holds long-form educational reflection insights in Persian.
    """
    __tablename__ = "knowledge_insights"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True)
    content = Column(Text)
    created_at = Column(String)                  # ISO format string

    user = relationship("User", back_populates="insights")

class UserSettings(Base):
    """
    Stores local settings, api key preferences, and active models.
    """
    __tablename__ = "user_settings"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True)
    name = Column(String, nullable=True)
    age = Column(String, nullable=True)
    education = Column(String, nullable=True)
    background_experience = Column(Text, nullable=True)
    additional_info = Column(Text, nullable=True)
    # API keys (never written to .env)
    gemini_api_key = Column(String, nullable=True)
    image_api_key = Column(String, nullable=True)
    # Per-user model names
    content_model = Column(String, nullable=True)    # course content generation
    coach_model = Column(String, nullable=True)      # session coach + course gen coach
    knowledge_model = Column(String, nullable=True)  # knowledge base / profiler AI
    image_model = Column(String, nullable=True)      # image generation model
    # Feature flags
    auto_generate_covers = Column(Boolean, nullable=True, default=False)

    user = relationship("User", back_populates="user_settings")

class UserProfile(Base):
    """
    Stores biografic traits utilized as static context for LLM personalizations.
    """
    __tablename__ = "user_profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True)
    name = Column(String, nullable=True)
    age = Column(String, nullable=True)
    education_level = Column(String, nullable=True)
    background_experience = Column(Text, nullable=True)
    primary_goals = Column(Text, nullable=True)
    additional_info = Column(Text, nullable=True)
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    
    user = relationship("User", back_populates="user_profile")
    cognitive_profile = relationship("CognitiveProfile", uselist=False, back_populates="user", cascade="all, delete-orphan")
    knowledge_nodes = relationship("KnowledgeNode", back_populates="user", cascade="all, delete-orphan")
    learning_events = relationship("LearningEventLog", back_populates="user", cascade="all, delete-orphan")

class CognitiveProfile(Base):
    """
    Represents dynamic cognitive parameters synthesized by the Profiler Agent.
    All rich summaries and recommendation fields are stored in Persian.
    """
    __tablename__ = "cognitive_profiles"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("user_profiles.id"), unique=True)
    
    global_learning_velocity = Column(Float, default=1.0)
    attention_span_minutes = Column(Integer, default=25)
    retention_index = Column(Float, default=0.8)
    
    cognitive_data_json = Column(Text, default='{}') 
    interests_json = Column(Text, default='[]')
    recommended_topics_json = Column(Text, default='[]')
    learning_style_summary = Column(Text, nullable=True)
    strength_areas_json = Column(Text, default='[]')
    personality_summary = Column(Text, nullable=True)
    
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    user = relationship("UserProfile", back_populates="cognitive_profile")

class KnowledgeNode(Base):
    """
    Represents an element in the conceptual mastery knowledge graph of the user.
    """
    __tablename__ = "knowledge_nodes"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("user_profiles.id"))
    
    concept = Column(String, index=True)
    category = Column(String, index=True)
    
    mastery_score = Column(Float, default=0.0) 
    confidence_level = Column(Float, default=0.5) 
    
    dependencies_json = Column(Text, default='{}')
    
    first_encountered = Column(DateTime, default=datetime.datetime.utcnow)
    last_tested = Column(DateTime, nullable=True)

    user = relationship("UserProfile", back_populates="knowledge_nodes")

class LearningEventLog(Base):
    """
    Log containing interactive micro-learning activities of the user.
    Stores semantic vector representations of individual learning events.
    """
    __tablename__ = "learning_event_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("user_profiles.id"))

    event_type = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)

    course_title = Column(String, nullable=True)
    session_title = Column(String, nullable=True)
    study_duration_seconds = Column(Integer, default=0)

    raw_interaction_text = Column(Text, nullable=True)
    vector_embedding_json = Column(Text, nullable=True)

    user = relationship("UserProfile", back_populates="learning_events")


class CourseEnrollment(Base):
    """
    Tracks a user's enrollment in a globally-published course.
    `source_course_id` is the original published course; `cloned_course_id`
    is the fresh raw copy added to the enrolling user's own Courses page.
    Used to guard against re-enrollment and to count enrollments per course.
    """
    __tablename__ = "course_enrollments"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    source_course_id = Column(Integer, ForeignKey("courses.id"), index=True, nullable=False)
    cloned_course_id = Column(Integer, ForeignKey("courses.id"), nullable=False)
    enrolled_at = Column(DateTime, default=datetime.datetime.utcnow)


class CourseRating(Base):
    """
    A user's 1–5 star rating on a globally-published course.
    One row per (user, source course); re-rating updates the existing row.
    """
    __tablename__ = "course_ratings"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    course_id = Column(Integer, ForeignKey("courses.id"), index=True, nullable=False)
    rating = Column(Integer, nullable=False)  # 1..5
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
